server.port=8080

# Ruta del volumen EFS en el contenedor Linux
app.efs.directory=/app/efs-data
app.efs.path=/app/efs

# Configuración limpia que leerá EXCLUSIVAMENTE de las variables de Docker
aws.access-key-id=${AWS_ACCESS_KEY_ID}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}
aws.session-token=${AWS_SESSION_TOKEN}
aws.region=${AWS_REGION}
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME}